import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";

import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter", // This creates a CSS variable
	display: "swap",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} font-sans`}>
				<div className="container">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
