import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RootLayout from "./RootLayout"; // Import the new client layout

import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${inter.variable} font-sans`}>
				<RootLayout>{children}</RootLayout>
			</body>
		</html>
	);
}
